version: '3.3'

services:

  microservice:
    image: sumelms/sumelms-classroom
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./config/config.yml:/config.yml
    depends_on:
      - postgres
    environment:
      - SUMELMS_CONFIG_PATH=/config.yml

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sumelms_classroom
    ports:
      - "5433:5432"
    volumes:
      - microservice_classroom_postgres:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  microservice_classroom_postgres: