server:
  http:
    host: ":8081"
rpcclients:
  courses:
    host: ":9000"
amqpclients:
  courses:
    host: "amqp://rabbitmq:secret@localhost:5672/"
database:
  driver: postgres
  host: localhost
  port: 5433
  username: postgres
  password: password
  database: sumelms_classroom
